import sys
import json
import os
import urllib.request
import urllib.error

def check_aigc(text):
    # Retrieve configuration from environment variables
    # Users will need to set these in their environment
    api_key = os.environ.get("AIGC_API_KEY", "")
    api_base = os.environ.get("AIGC_API_BASE", "")

    if not api_key or not api_base:
        print("Error: AIGC_API_KEY or AIGC_API_BASE environment variables not set.")
        print("Please configure them before running the AIGC detection.")
        # We don't fail hard here so the skill can gracefully handle the missing config
        sys.exit(0)

    # Ensure api_base ends with a slash or doesn't, depending on the expected endpoint
    # This is a generic implementation. You might need to adjust the payload
    # and endpoint based on the specific AIGC detection API you plan to use.
    endpoint = f"{api_base.rstrip('/')}/v1/chat/completions" # Defaulting to OpenAI compatible endpoint

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }

    # Generic prompt to ask an LLM to detect if text is AI generated
    # If you are using a dedicated detection API, you would change this payload
    payload = {
        "model": "gpt-4o-mini", # Replace with your preferred model
        "messages": [
            {"role": "system", "content": "You are an expert at detecting AI-generated content (AIGC). Analyze the following text and determine the probability (0-100%) that it was generated by an AI. Provide only the percentage number."},
            {"role": "user", "content": text}
        ],
        "temperature": 0.1
    }

    data = json.dumps(payload).encode('utf-8')

    req = urllib.request.Request(endpoint, data=data, headers=headers)

    try:
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode('utf-8'))

            # Assuming standard OpenAI response format
            if "choices" in result and len(result["choices"]) > 0:
                answer = result["choices"][0]["message"]["content"].strip()
                print(f"AIGC Probability: {answer}")
                # You can add logic here to fail the script if probability is too high
                # if float(answer.replace('%', '')) > 80:
                #     sys.exit(1)
            else:
                print("Unexpected API response format.")
                sys.exit(1)

    except urllib.error.HTTPError as e:
        print(f"API Request failed: {e.code} {e.reason}")
        print(e.read().decode('utf-8'))
        sys.exit(1)
    except Exception as e:
        print(f"An error occurred: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python check_aigc.py \"<text_to_check>\"")
        sys.exit(1)

    text_to_check = sys.argv[1]
    check_aigc(text_to_check)
